# Generated by Django 2.2.10 on 2020-06-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
